packages:
  - 'apps/api'
  - 'apps/merchant-portal'
  - 'packages/*'

catalogs:
  dependencies:
    # Core
    typescript: ^5.3.0
    
    # NestJS & Backend
    '@nestjs/common': ^10.2.0
    '@nestjs/core': ^10.2.0
    '@nestjs/platform-express': ^10.2.0
    '@nestjs/typeorm': ^10.0.0
    '@nestjs/jwt': ^11.0.0
    '@nestjs/passport': ^10.0.0
    'typeorm': ^0.3.17
    'mysql2': ^3.6.0
    'redis': ^4.6.0
    'bullmq': ^4.11.0
    'bcryptjs': ^2.4.3
    'argon2': ^0.31.0
    'jsonwebtoken': ^9.1.0
    'passport': ^0.7.0
    'passport-jwt': ^4.0.1
    'class-validator': ^0.14.0
    'class-transformer': ^0.5.1
    'helmet': ^7.1.0
    'express-rate-limit': ^7.1.0
    '@nestjs/swagger': ^7.1.0
    'swagger-ui-express': ^5.0.0
    'winston': ^3.11.0
    'pino': ^8.17.0
    
    # Next.js & Frontend
    'next': ^14.0.0
    'react': ^18.2.0
    'react-dom': ^18.2.0
    'tailwindcss': ^3.3.0
    'postcss': ^8.4.31
    'autoprefixer': ^10.4.16
    '@headlessui/react': ^1.7.17
    '@radix-ui/react-dialog': ^1.1.1
    '@radix-ui/react-dropdown-menu': ^2.0.6
    '@radix-ui/react-slot': ^2.0.2
    'clsx': ^2.0.0
    'tailwind-merge': ^2.2.0
    'lucide-react': ^0.294.0
    '@tanstack/react-query': ^5.25.0
    'react-hook-form': ^7.48.0
    'zod': ^3.22.4
    '@hookform/resolvers': ^3.3.2
    'recharts': ^2.10.0
    'axios': ^1.6.0
    'next-intl': ^2.17.0
    
    # React Native & Expo (Excluded for now - use separate installation)
    # 'expo': ^49.0.0
    # 'react-native': ^0.72.0
    # 'react-native-web': ^0.18.0
    # 'expo-router': ^2.0.0
    # 'react-navigation': ^6.1.0
    # '@react-navigation/native': ^6.1.0
    # '@react-navigation/bottom-tabs': ^6.5.0
    # '@react-navigation/stack': ^6.3.0
    # 'nativewind': ^2.0.0
    # 'expo-splash-screen': ^0.20.0
    # 'expo-status-bar': ^1.6.0
    
    # Testing
    'jest': ^29.7.0
    '@types/jest': ^29.5.8
    'supertest': ^6.3.3
    '@types/supertest': ^2.0.12
    'ts-jest': ^29.1.1
    
    # Utilities
    'dotenv': ^16.3.1
    'uuid': ^9.0.1
    'date-fns': ^2.30.0
    'lodash': ^4.17.21
    
    # Development
    'eslint': ^8.54.0
    '@typescript-eslint/eslint-plugin': ^6.13.0
    '@typescript-eslint/parser': ^6.13.0
    'prettier': ^3.1.0
    'husky': ^8.0.3
    'lint-staged': ^15.2.0

